### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [trisyoungs/dissolve#126]
https://github.com/trisyoungs/dissolve/releases/download/continuous/Dissolve-GUI-0.5.3-98a899f0-x86_64.AppImage is no longer available

Reference:
https://github.com/AppImage/appimage.github.io/pull/1847

**Comment by trisyoungs** [comment]
The release you're linking to is a continuous build, tagged with the short hash. As such it's volatile, and shouldn't be linked to. Long-lived, versioned releases will appear as the project develops following its initial release, and are tagged with the version number MAJOR.MINOR.PATCH.
